name: Update Submodule (Cron)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Every hour, you can adjust this according to your needs

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Check for updates
      id: check_updates
      run: |
        UPDATED=$(git status --porcelain)
        if [ -z "$UPDATED" ]; then
          echo "updated=false" >> $GITHUB_OUTPUT
        else
          echo "updated=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Commit and push changes
      if: steps.check_updates.outputs.updated == 'true'
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
